In [17]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [18]:
#https://docs.google.com/spreadsheets/d/1VyT-XULubCS49aeHxnWwtNOk4alFXGLuaI4VgV9D-Ng/edit#gid=811491291
gsheetid = "1VyT-XULubCS49aeHxnWwtNOk4alFXGLuaI4VgV9D-Ng"
sheet_name = "Salesdata"

In [19]:
gsheet_url = "https://docs.google.com/spreadsheets/d/{}/gviz/tq?tqx=out:csv&sheet={}".format(gsheetid, sheet_name)

In [20]:
gsheet_url

'https://docs.google.com/spreadsheets/d/1VyT-XULubCS49aeHxnWwtNOk4alFXGLuaI4VgV9D-Ng/gviz/tq?tqx=out:csv&sheet=Salesdata'

In [21]:
df = pd.read_csv(gsheet_url)

In [22]:
df

CPI  discounts  offers   Sales
0  2600          3      20  550000
1  3000          4      15  565000
2  3200          5      18  610000
3  3600          3      30  595000
4  4000          5       8  760000
5  4100          6       8  810000

In [26]:
import pandas as pd
from sklearn import linear_model

# Assuming you have already loaded the DataFrame df from the Google Sheets link

# Assuming 'Sales' is the target column
X = df.drop('Sales', axis='columns')
y = df.Sales

# Create a linear regression model
reg = linear_model.LinearRegression()

# Fit the model to the data
reg.fit(X, y)


LinearRegression()

In [27]:
reg.coef_

array([  128.43512778,  5913.51964731, -4902.54602054])

In [28]:
reg.intercept_

264780.07095467095

In [29]:
 # Given below information find out the Sales that has
  # 5000 cpi , 3 percentage discounts, 20 rewards offers
reg.predict([[5000,3,20]])


C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([826645.34838222])

In [31]:
128.43512778*5000 + 5913.51964731*3 + -4902.54602054*20 + 264780.07095467095

826645.3483858008

In [32]:
  #4000 cpi , 8 percentage discounts, 19 rewards offers
reg.predict([[4000,8,19]])    

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([732680.36486005])

In [33]:
128.43512778*4000 + 5913.51964731*8 + -4902.54602054*19 + 264780.07095467095

732680.3648628908

In [34]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Assuming you have a DataFrame named 'df' with the given data
data = {
    'CPI': [2600, 3000, 3200, 3600, 4000, 4100],
    'discounts': [3, 4, 5, 3, 5, 6],
    'offers': [20, 15, 18, 30, 8, 8],
    'Sales': [550000, 565000, 610000, 595000, 760000, 810000]
}

df = pd.DataFrame(data)

# Separate features (X) and target variable (y)
X = df[['CPI', 'discounts', 'offers']]
y = df['Sales']

# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=30)

# Print the shapes of the resulting sets
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)


X_train shape: (4, 3)
X_test shape: (2, 3)
y_train shape: (4,)
y_test shape: (2,)
